apiVersion: v1
kind: Service
metadata:
  name: {{.Values.application.name}}
  labels:
    job: api-service # added for prometheus servicemonitor
    app: {{.Values.application.name}}
    run: {{.Values.application.name}}
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8000
  selector:
    app: {{.Values.application.name}}
  type: NodePort

